# version: 0.2

# phases:
#   install:
#     commands:
#       - echo Installing dependencies...
#       - npm install
#   pre_build:
#     commands:
#       - echo Running tests...
#       - npm test
#   build:
#     commands:
#       - echo Build complete.

# artifacts:
#   files:
#     - src/*
#     - tests/*
#   discard-paths: yes

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Running Tests
      - npm test
  post_build:
    commands:
      - echo Tests Complete