version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd my-react-app && npm install  # Navigate to the React app folder and install dependencies
  build:
    commands:
      - cd my-react-app && CI=false npm test -- --coverage  # Run tests in the React app
artifacts:
  base-directory: my-react-app/build  # Specify where the build artifacts are generated
  files:
    - '**/*'
